nexus:
  build: ./nexus
  container_name: nexus
  ports:
    - "18081:8081"
jenkins:
  build: ./jenkins
  container_name: jenkins
  privileged: true
  ports:
    - "18080:8080"
  links:
    - nexus:nexus
    - sonar:sonar
    - gitlab:gitlab
    - nginx:nginx
  volumes:
    - /var/docker/volumes/jenkins_home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /lib/x86_64-linux-gnu/libdevmapper.so.1.02.1:/lib/x86_64-linux-gnu/libdevmapper.so.1.02.1
sonar:
  build: ./sonar
  container_name: sonar
  ports:
   - "19000:9000"
   - "5432:5432"
  environment:
   - SONARQUBE_JDBC_USERNAME=db_user
   - SONARQUBE_JDBC_PASSWORD=db_pass
   - SONARQUBE_JDBC_URL=jdbc:postgresql://localhost:5432/sonar
postgresql:
  image: sameersbn/postgresql:9.4-3
  net: container:sonar
  environment:
    - DB_USER=db_user
    - DB_PASS=db_pass
    - DB_NAME=sonar,gitlab
  volumes:
    - /var/docker/volumes/postgresql:/var/lib/postgresql
gitlab:
  build: ./gitlab
  container_name: gitlab
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - TZ=GMT
    - GITLAB_TIMEZONE=GMT

    - DB_NAME=gitlab
    - DB_USER=db_user
    - DB_PASS=db_pass

    - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string

    - GITLAB_HOST=192.168.1.18
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=notifications@example.com
    - GITLAB_EMAIL_REPLY_TO=noreply@example.com
    - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

    - GITLAB_BACKUPS=daily
    - GITLAB_BACKUP_TIME=11:58

    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_STARTTLS=false
  volumes:
    - /var/docker/volumes/gitlab/gitlab:/home/git/data
redis:
  image: sameersbn/redis:latest
  volumes:
    - /var/docker/volumes/gitlab/redis:/var/lib/redis
nginx:
  build: ./nginx
  container_name: nginx
  ports:
    - "15000:5000"
  links:
    - registry:registry
registry:
  container_name: registry
  image: registry:2.3.1
